name: jarvision
description: Flutter frontend for PiggyBank

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  toggle_switch: ^2.1.0
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^4.3.0
  shared_preferences: ^2.2.0
  crypto: ^3.0.3
  fluttertoast: ^8.2.2
  cloud_firestore: ^4.8.4
  flutter_blurhash: ^0.7.0
  introduction_slider: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

